export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const STORE_RESULTS = 'STORE_RESULTS'
export const DELETE_RESULT = 'DELETE_RESULT '
export const SUBTRACT = 'SUBTRACT'
